export const GOOGLE_DRIVE_CLIENT_ID = process.env['GOOGLE_DRIVE_CLIENT_ID']
export const GOOGLE_DRIVE_CLIENT_SECRET = process.env['GOOGLE_DRIVE_CLIENT_SECRET']
export const GOOGLE_DRIVE_REDIRECT_URI = process.env['GOOGLE_DRIVE_REDIRECT_URI']
export const GOOGLE_DRIVE_REFRESH_TOKEN = process.env['GOOGLE_DRIVE_REFRESH_TOKEN']
export const GMAIL_REFRESH_TOKEN = process.env['GMAIL_REFRESH_TOKEN']
export const SHEET_PDF_PATH = process.env['SHEET_PDF_PATH']



